[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"

auto_detect_solc = true

additional_compiler_profiles = [ 
    { name = "optimizer_runs", optimizer_runs = 44444444 },
    { name = "optimizer", optimizer = false }
]

compilation_restrictions = [
  { paths = "src/LiquidityLauncher.sol", optimizer = true, optimizer_runs = 44444444 },
  { paths = "src/distributionStrategies/LBPStrategyBasicFactory.sol", optimizer = false}
]

[profile.default.fuzz]
runs = 1000

[profile.ci.fuzz]
runs = 2500

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
