[profile.default]
optimizer = true
optimizer_runs = 44444444
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"

auto_detect_solc = true

additional_compiler_profiles = [ { name = "optimizer_runs", optimizer_runs = 1 } ]

compilation_restrictions = [
  { paths = "src/distributionContracts/LBPStrategyBasic.sol", optimizer = true, optimizer_runs = 1 },
  { paths = "src/distributionContracts/VirtualLBPStrategyBasic.sol", optimizer = true, optimizer_runs = 1 },
  { paths = "src/distributionStrategies/LBPStrategyBasicFactory.sol", optimizer = true, optimizer_runs = 1 },
  { paths = "src/distributionContracts/VirtualLBPStrategyFactory.sol", optimizer = true, optimizer_runs = 1 }
]

[profile.default.fuzz]
runs = 1000

[profile.ci.fuzz]
runs = 2500

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
