[profile.default]
optimizer_runs = 50000000
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
bytecode_hash = "none"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
