[profile.default]
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"
fs_permissions = [
  { access = "read", path = "script/" }
]

auto_detect_solc = true

[profile.default.fuzz]
runs = 1000

[profile.ci.fuzz]
runs = 2500

[lint]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
